version: '3.9'

services:
  db:
    image: surrealdb/surrealdb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'rental'
      POSTGRES_DB: 'rental'
    volumes:
      - db-data:/var/lib/surrealdb/data
    restart: always
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - db
volumes:
  db-data:
